# IPC Generator Configuration for Basic Template
# Run: electron-ipc-generate --config ipc-config.yaml

apis:
  - name: api
    input: ./ipc-api.ts
    output: ./ipc-api.generated.ts
    mainBroadcastOutput: ./ipc-api-main-broadcast.ts
    contracts:
      invoke: InvokeContracts
      event: EventContracts
      send: BroadcastContracts
      streamDownload: StreamDownloadContracts
